spring:
  application:
    name: api-gateway
server:
  instanceId: api-gateway
  port : 8762
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
zuul:
  routes:
    emp-api:      
      path: /emp-api/**
    prj-api:
      path: /prj-api/**
     
emp-api:
  ribbon:
    listOfServers: http://localhost:5001
    
prj-api:
  ribbon:
    listOfServers: http://localhost:5002
          
#hystrix:		# circuit breaker
#  command:
#    member-api:
#      execution:
#        isolation:
#          thread:
#            # Ribbon의 각 timeout보다 커야 기대하는대로 동작함
#            timeoutInMilliseconds: 5000 


#    ConnectTimeout: 1000
#    ReadTimeout: 3000
#    MaxTotalHttpConnections: 500
#    MaxConnectionsPerHost: 100