spring:#  profiles:#    active: default
  application:
    name: api-gateway    
server:
  port : 8762  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka      
zuul:
  routes:
    emp-api:      
      path: /emp-api/**
    prj-api:
      path: /prj-api/**
